/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 65
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 46
#define ALIAS_COUNT 0
#define TOKEN_COUNT 28
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 13
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 10
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_let = 1,
  anon_sym_EQ = 2,
  anon_sym_PLUS = 3,
  anon_sym_DASH = 4,
  anon_sym_STAR = 5,
  anon_sym_SLASH = 6,
  anon_sym_EQ_EQ = 7,
  anon_sym_LT = 8,
  anon_sym_GT = 9,
  anon_sym_and = 10,
  anon_sym_or = 11,
  anon_sym_not = 12,
  anon_sym_if = 13,
  anon_sym_then = 14,
  anon_sym_else = 15,
  anon_sym_in = 16,
  anon_sym_fn = 17,
  anon_sym_LPAREN = 18,
  anon_sym_RPAREN = 19,
  anon_sym_DASH_GT = 20,
  anon_sym_COMMA = 21,
  sym_integer = 22,
  anon_sym_true = 23,
  anon_sym_false = 24,
  sym_identifier = 25,
  anon_sym_POUND = 26,
  aux_sym_comment_token1 = 27,
  sym_source_file = 28,
  sym__definition = 29,
  sym_let_definition = 30,
  sym__expression = 31,
  sym_binary_expression = 32,
  sym_unary_expression = 33,
  sym_if_expression = 34,
  sym_let_expression = 35,
  sym_fn_expression = 36,
  sym_parameter_list = 37,
  sym_application = 38,
  sym_argument_list = 39,
  sym_parenthesized_expression = 40,
  sym_boolean = 41,
  sym_comment = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_parameter_list_repeat1 = 44,
  aux_sym_argument_list_repeat1 = 45,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_STAR] = "*",
  [anon_sym_SLASH] = "/",
  [anon_sym_EQ_EQ] = "==",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_and] = "and",
  [anon_sym_or] = "or",
  [anon_sym_not] = "not",
  [anon_sym_if] = "if",
  [anon_sym_then] = "then",
  [anon_sym_else] = "else",
  [anon_sym_in] = "in",
  [anon_sym_fn] = "fn",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_COMMA] = ",",
  [sym_integer] = "integer",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_identifier] = "identifier",
  [anon_sym_POUND] = "#",
  [aux_sym_comment_token1] = "comment_token1",
  [sym_source_file] = "source_file",
  [sym__definition] = "_definition",
  [sym_let_definition] = "let_definition",
  [sym__expression] = "_expression",
  [sym_binary_expression] = "binary_expression",
  [sym_unary_expression] = "unary_expression",
  [sym_if_expression] = "if_expression",
  [sym_let_expression] = "let_expression",
  [sym_fn_expression] = "fn_expression",
  [sym_parameter_list] = "parameter_list",
  [sym_application] = "application",
  [sym_argument_list] = "argument_list",
  [sym_parenthesized_expression] = "parenthesized_expression",
  [sym_boolean] = "boolean",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_argument_list_repeat1] = "argument_list_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_STAR] = anon_sym_STAR,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [anon_sym_EQ_EQ] = anon_sym_EQ_EQ,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_and] = anon_sym_and,
  [anon_sym_or] = anon_sym_or,
  [anon_sym_not] = anon_sym_not,
  [anon_sym_if] = anon_sym_if,
  [anon_sym_then] = anon_sym_then,
  [anon_sym_else] = anon_sym_else,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_fn] = anon_sym_fn,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_integer] = sym_integer,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_identifier] = sym_identifier,
  [anon_sym_POUND] = anon_sym_POUND,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [sym_source_file] = sym_source_file,
  [sym__definition] = sym__definition,
  [sym_let_definition] = sym_let_definition,
  [sym__expression] = sym__expression,
  [sym_binary_expression] = sym_binary_expression,
  [sym_unary_expression] = sym_unary_expression,
  [sym_if_expression] = sym_if_expression,
  [sym_let_expression] = sym_let_expression,
  [sym_fn_expression] = sym_fn_expression,
  [sym_parameter_list] = sym_parameter_list,
  [sym_application] = sym_application,
  [sym_argument_list] = sym_argument_list,
  [sym_parenthesized_expression] = sym_parenthesized_expression,
  [sym_boolean] = sym_boolean,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_argument_list_repeat1] = aux_sym_argument_list_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_and] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_or] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_not] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_then] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_fn] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_POUND] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__definition] = {
    .visible = false,
    .named = true,
  },
  [sym_let_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_binary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_unary_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_if_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_let_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_fn_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym_argument_list] = {
    .visible = true,
    .named = true,
  },
  [sym_parenthesized_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_argument_list_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_alternative = 1,
  field_arguments = 2,
  field_body = 3,
  field_condition = 4,
  field_consequence = 5,
  field_function = 6,
  field_left = 7,
  field_name = 8,
  field_operand = 9,
  field_operator = 10,
  field_parameters = 11,
  field_right = 12,
  field_value = 13,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_alternative] = "alternative",
  [field_arguments] = "arguments",
  [field_body] = "body",
  [field_condition] = "condition",
  [field_consequence] = "consequence",
  [field_function] = "function",
  [field_left] = "left",
  [field_name] = "name",
  [field_operand] = "operand",
  [field_operator] = "operator",
  [field_parameters] = "parameters",
  [field_right] = "right",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 3},
  [4] = {.index = 6, .length = 1},
  [5] = {.index = 7, .length = 2},
  [6] = {.index = 9, .length = 1},
  [7] = {.index = 10, .length = 3},
  [8] = {.index = 13, .length = 3},
  [9] = {.index = 16, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 1},
    {field_value, 3},
  [2] =
    {field_operand, 1},
  [3] =
    {field_left, 0},
    {field_operator, 1},
    {field_right, 2},
  [6] =
    {field_function, 0},
  [7] =
    {field_arguments, 2},
    {field_function, 0},
  [9] =
    {field_body, 4},
  [10] =
    {field_body, 5},
    {field_name, 1},
    {field_value, 3},
  [13] =
    {field_alternative, 5},
    {field_condition, 1},
    {field_consequence, 3},
  [16] =
    {field_body, 5},
    {field_parameters, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '#', 74,
        '(', 52,
        ')', 53,
        '*', 36,
        '+', 33,
        ',', 55,
        '-', 35,
        '/', 37,
        '<', 39,
        '=', 32,
        '>', 40,
        'a', 17,
        'e', 15,
        'f', 5,
        'i', 12,
        'l', 7,
        'n', 20,
        'o', 21,
        't', 14,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 1:
      ADVANCE_MAP(
        '#', 74,
        '(', 52,
        ')', 53,
        '-', 34,
        '=', 31,
        'f', 61,
        'i', 65,
        'l', 62,
        'n', 67,
        't', 68,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 2:
      if (lookahead == '#') ADVANCE(74);
      if (lookahead == ')') ADVANCE(53);
      if (lookahead == '-') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 3:
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(54);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(50);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(41);
      END_STATE();
    case 7:
      if (lookahead == 'e') ADVANCE(24);
      END_STATE();
    case 8:
      if (lookahead == 'e') ADVANCE(48);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(57);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(19);
      END_STATE();
    case 12:
      if (lookahead == 'f') ADVANCE(45);
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 13:
      if (lookahead == 'h') ADVANCE(11);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(11);
      if (lookahead == 'r') ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 17:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 18:
      if (lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 19:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 20:
      if (lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(42);
      END_STATE();
    case 22:
      if (lookahead == 's') ADVANCE(8);
      END_STATE();
    case 23:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 24:
      if (lookahead == 't') ADVANCE(29);
      END_STATE();
    case 25:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 26:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '#', 74,
        '(', 52,
        ')', 53,
        '*', 36,
        '+', 33,
        ',', 55,
        '-', 34,
        '/', 37,
        '<', 39,
        '=', 3,
        '>', 40,
        'a', 17,
        'e', 15,
        'i', 18,
        'l', 7,
        'o', 21,
        't', 13,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_let);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      if (lookahead == '=') ADVANCE(38);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '>') ADVANCE(54);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_SLASH);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_EQ_EQ);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_and);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_or);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_not);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_not);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_if);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_then);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_fn);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_fn);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_true);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_false);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(66);
      if (lookahead == 'n') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(70);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(60);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(46);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(69);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'o') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(72);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(44);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(63);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(anon_sym_POUND);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_POUND);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '#') ADVANCE(75);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(76);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(77);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 1},
  [3] = {.lex_state = 1},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 27},
  [20] = {.lex_state = 27},
  [21] = {.lex_state = 27},
  [22] = {.lex_state = 27},
  [23] = {.lex_state = 27},
  [24] = {.lex_state = 27},
  [25] = {.lex_state = 27},
  [26] = {.lex_state = 27},
  [27] = {.lex_state = 27},
  [28] = {.lex_state = 27},
  [29] = {.lex_state = 27},
  [30] = {.lex_state = 27},
  [31] = {.lex_state = 27},
  [32] = {.lex_state = 27},
  [33] = {.lex_state = 27},
  [34] = {.lex_state = 27},
  [35] = {.lex_state = 27},
  [36] = {.lex_state = 27},
  [37] = {.lex_state = 27},
  [38] = {.lex_state = 27},
  [39] = {.lex_state = 27},
  [40] = {.lex_state = 27},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 2},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 76},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {(TSStateId)(-1),},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [anon_sym_SLASH] = ACTIONS(1),
    [anon_sym_EQ_EQ] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_and] = ACTIONS(1),
    [anon_sym_or] = ACTIONS(1),
    [anon_sym_not] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_then] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_fn] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_POUND] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym__definition] = STATE(51),
    [sym_let_definition] = STATE(49),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(41),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_POUND] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(21), 1,
      anon_sym_RPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(2), 1,
      sym_comment,
    STATE(34), 1,
      sym__expression,
    STATE(53), 1,
      sym_argument_list,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [54] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(3), 1,
      sym_comment,
    STATE(36), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [102] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(4), 1,
      sym_comment,
    STATE(20), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [150] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(5), 1,
      sym_comment,
    STATE(40), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [198] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(6), 1,
      sym_comment,
    STATE(39), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [246] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(7), 1,
      sym_comment,
    STATE(22), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [294] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(8), 1,
      sym_comment,
    STATE(23), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [342] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(9), 1,
      sym_comment,
    STATE(19), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [390] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(10), 1,
      sym_comment,
    STATE(33), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [438] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(11), 1,
      sym_comment,
    STATE(24), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [486] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(12), 1,
      sym_comment,
    STATE(37), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [534] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(13), 1,
      sym_comment,
    STATE(38), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [582] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(14), 1,
      sym_comment,
    STATE(29), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [630] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(15), 1,
      sym_comment,
    STATE(35), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [678] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(16), 1,
      sym_comment,
    STATE(30), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [726] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(17), 1,
      sym_comment,
    STATE(31), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [774] = 13,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(9), 1,
      anon_sym_let,
    ACTIONS(11), 1,
      anon_sym_DASH,
    ACTIONS(13), 1,
      anon_sym_not,
    ACTIONS(15), 1,
      anon_sym_if,
    ACTIONS(17), 1,
      anon_sym_fn,
    ACTIONS(19), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      sym_integer,
    ACTIONS(27), 1,
      sym_identifier,
    STATE(18), 1,
      sym_comment,
    STATE(32), 1,
      sym__expression,
    ACTIONS(25), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(27), 8,
      sym_binary_expression,
      sym_unary_expression,
      sym_if_expression,
      sym_let_expression,
      sym_fn_expression,
      sym_application,
      sym_parenthesized_expression,
      sym_boolean,
  [822] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(19), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 12,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [854] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(20), 1,
      sym_comment,
    ACTIONS(37), 16,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [882] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(21), 1,
      sym_comment,
    ACTIONS(39), 17,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [908] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(22), 1,
      sym_comment,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(29), 14,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [938] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(23), 1,
      sym_comment,
    ACTIONS(29), 16,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [966] = 8,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    STATE(24), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(29), 8,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1002] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(25), 1,
      sym_comment,
    ACTIONS(45), 17,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1028] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(26), 1,
      sym_comment,
    ACTIONS(47), 17,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1054] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(27), 1,
      sym_comment,
    ACTIONS(49), 17,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1080] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(28), 1,
      sym_comment,
    ACTIONS(51), 17,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_STAR,
      anon_sym_SLASH,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1106] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    STATE(29), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(53), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1144] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    STATE(30), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(57), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1182] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    STATE(31), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(59), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1220] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    STATE(32), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(61), 7,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1258] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    STATE(33), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
    ACTIONS(29), 9,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_and,
      anon_sym_or,
      anon_sym_then,
      anon_sym_else,
      anon_sym_in,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1292] = 11,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    ACTIONS(63), 1,
      anon_sym_RPAREN,
    ACTIONS(65), 1,
      anon_sym_COMMA,
    STATE(34), 1,
      sym_comment,
    STATE(46), 1,
      aux_sym_argument_list_repeat1,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
  [1330] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    STATE(35), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(67), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
  [1363] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    STATE(36), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(69), 2,
      ts_builtin_sym_end,
      anon_sym_let,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
  [1396] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    ACTIONS(71), 1,
      anon_sym_else,
    STATE(37), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
  [1428] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    ACTIONS(73), 1,
      anon_sym_in,
    STATE(38), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
  [1460] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(39), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
  [1492] = 9,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(35), 1,
      anon_sym_LPAREN,
    ACTIONS(43), 1,
      anon_sym_and,
    ACTIONS(55), 1,
      anon_sym_or,
    ACTIONS(77), 1,
      anon_sym_then,
    STATE(40), 1,
      sym_comment,
    ACTIONS(31), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(33), 2,
      anon_sym_STAR,
      anon_sym_SLASH,
    ACTIONS(41), 3,
      anon_sym_EQ_EQ,
      anon_sym_LT,
      anon_sym_GT,
  [1524] = 7,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(41), 1,
      sym_comment,
    STATE(42), 1,
      aux_sym_source_file_repeat1,
    STATE(49), 1,
      sym_let_definition,
    STATE(51), 1,
      sym__definition,
  [1546] = 6,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 1,
      anon_sym_let,
    STATE(49), 1,
      sym_let_definition,
    STATE(51), 1,
      sym__definition,
    STATE(42), 2,
      sym_comment,
      aux_sym_source_file_repeat1,
  [1566] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(86), 1,
      anon_sym_RPAREN,
    ACTIONS(88), 1,
      sym_identifier,
    STATE(43), 1,
      sym_comment,
    STATE(52), 1,
      sym_parameter_list,
  [1582] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(90), 1,
      anon_sym_RPAREN,
    ACTIONS(92), 1,
      anon_sym_COMMA,
    STATE(44), 1,
      sym_comment,
    STATE(47), 1,
      aux_sym_parameter_list_repeat1,
  [1598] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(94), 1,
      anon_sym_RPAREN,
    ACTIONS(96), 1,
      anon_sym_COMMA,
    STATE(45), 2,
      sym_comment,
      aux_sym_parameter_list_repeat1,
  [1612] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(65), 1,
      anon_sym_COMMA,
    ACTIONS(99), 1,
      anon_sym_RPAREN,
    STATE(46), 1,
      sym_comment,
    STATE(48), 1,
      aux_sym_argument_list_repeat1,
  [1628] = 5,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(92), 1,
      anon_sym_COMMA,
    ACTIONS(101), 1,
      anon_sym_RPAREN,
    STATE(45), 1,
      aux_sym_parameter_list_repeat1,
    STATE(47), 1,
      sym_comment,
  [1644] = 4,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    STATE(48), 2,
      sym_comment,
      aux_sym_argument_list_repeat1,
  [1658] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(49), 1,
      sym_comment,
    ACTIONS(106), 2,
      ts_builtin_sym_end,
      anon_sym_let,
  [1669] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(50), 1,
      sym_comment,
    ACTIONS(94), 2,
      anon_sym_RPAREN,
      anon_sym_COMMA,
  [1680] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    STATE(51), 1,
      sym_comment,
    ACTIONS(108), 2,
      ts_builtin_sym_end,
      anon_sym_let,
  [1691] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(110), 1,
      anon_sym_RPAREN,
    STATE(52), 1,
      sym_comment,
  [1701] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(112), 1,
      anon_sym_RPAREN,
    STATE(53), 1,
      sym_comment,
  [1711] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(114), 1,
      anon_sym_EQ,
    STATE(54), 1,
      sym_comment,
  [1721] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(116), 1,
      ts_builtin_sym_end,
    STATE(55), 1,
      sym_comment,
  [1731] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(118), 1,
      anon_sym_LPAREN,
    STATE(56), 1,
      sym_comment,
  [1741] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(120), 1,
      sym_identifier,
    STATE(57), 1,
      sym_comment,
  [1751] = 3,
    ACTIONS(122), 1,
      anon_sym_POUND,
    ACTIONS(124), 1,
      aux_sym_comment_token1,
    STATE(58), 1,
      sym_comment,
  [1761] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(126), 1,
      anon_sym_DASH_GT,
    STATE(59), 1,
      sym_comment,
  [1771] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(128), 1,
      anon_sym_EQ,
    STATE(60), 1,
      sym_comment,
  [1781] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(130), 1,
      sym_identifier,
    STATE(61), 1,
      sym_comment,
  [1791] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(132), 1,
      sym_identifier,
    STATE(62), 1,
      sym_comment,
  [1801] = 3,
    ACTIONS(3), 1,
      anon_sym_POUND,
    ACTIONS(134), 1,
      anon_sym_DASH_GT,
    STATE(63), 1,
      sym_comment,
  [1811] = 1,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 54,
  [SMALL_STATE(4)] = 102,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 198,
  [SMALL_STATE(7)] = 246,
  [SMALL_STATE(8)] = 294,
  [SMALL_STATE(9)] = 342,
  [SMALL_STATE(10)] = 390,
  [SMALL_STATE(11)] = 438,
  [SMALL_STATE(12)] = 486,
  [SMALL_STATE(13)] = 534,
  [SMALL_STATE(14)] = 582,
  [SMALL_STATE(15)] = 630,
  [SMALL_STATE(16)] = 678,
  [SMALL_STATE(17)] = 726,
  [SMALL_STATE(18)] = 774,
  [SMALL_STATE(19)] = 822,
  [SMALL_STATE(20)] = 854,
  [SMALL_STATE(21)] = 882,
  [SMALL_STATE(22)] = 908,
  [SMALL_STATE(23)] = 938,
  [SMALL_STATE(24)] = 966,
  [SMALL_STATE(25)] = 1002,
  [SMALL_STATE(26)] = 1028,
  [SMALL_STATE(27)] = 1054,
  [SMALL_STATE(28)] = 1080,
  [SMALL_STATE(29)] = 1106,
  [SMALL_STATE(30)] = 1144,
  [SMALL_STATE(31)] = 1182,
  [SMALL_STATE(32)] = 1220,
  [SMALL_STATE(33)] = 1258,
  [SMALL_STATE(34)] = 1292,
  [SMALL_STATE(35)] = 1330,
  [SMALL_STATE(36)] = 1363,
  [SMALL_STATE(37)] = 1396,
  [SMALL_STATE(38)] = 1428,
  [SMALL_STATE(39)] = 1460,
  [SMALL_STATE(40)] = 1492,
  [SMALL_STATE(41)] = 1524,
  [SMALL_STATE(42)] = 1546,
  [SMALL_STATE(43)] = 1566,
  [SMALL_STATE(44)] = 1582,
  [SMALL_STATE(45)] = 1598,
  [SMALL_STATE(46)] = 1612,
  [SMALL_STATE(47)] = 1628,
  [SMALL_STATE(48)] = 1644,
  [SMALL_STATE(49)] = 1658,
  [SMALL_STATE(50)] = 1669,
  [SMALL_STATE(51)] = 1680,
  [SMALL_STATE(52)] = 1691,
  [SMALL_STATE(53)] = 1701,
  [SMALL_STATE(54)] = 1711,
  [SMALL_STATE(55)] = 1721,
  [SMALL_STATE(56)] = 1731,
  [SMALL_STATE(57)] = 1741,
  [SMALL_STATE(58)] = 1751,
  [SMALL_STATE(59)] = 1761,
  [SMALL_STATE(60)] = 1771,
  [SMALL_STATE(61)] = 1781,
  [SMALL_STATE(62)] = 1791,
  [SMALL_STATE(63)] = 1801,
  [SMALL_STATE(64)] = 1811,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binary_expression, 3, 0, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unary_expression, 2, 0, 2),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parenthesized_expression, 3, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 3, 0, 4),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 4, 0, 5),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_expression, 5, 0, 6),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_expression, 6, 0, 7),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_expression, 6, 0, 8),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_fn_expression, 6, 0, 9),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 1, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [67] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_definition, 4, 0, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [88] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [94] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_argument_list, 2, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 2, 0, 0),
  [103] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_argument_list_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__definition, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [116] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [124] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_lark(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "lark",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
